### ISSUE TITLE
Code highlighting less scannable

### ISSUE THREAD

**Issue by katrinkerber** [barrelstrength/Craft-Twig.tmbundle#13]
Thank you very much for the recent updates to this :)

In Sublime Text, I find that the code within Twig tags is no longer highlighted as clearly as it was in version 1, making it harder to read/scan.

Version 1 examples:
![screen shot 2015-06-23 at 09 00 56](https://cloud.githubusercontent.com/assets/818635/8301533/6bf40758-1986-11e5-94bd-f7ad450b41cb.png)

![screen shot 2015-06-23 at 08 56 01](https://cloud.githubusercontent.com/assets/818635/8301503/2c833c7e-1986-11e5-802c-685bf3f31ebf.png)

Version 2:
![screen shot 2015-06-23 at 08 57 12](https://cloud.githubusercontent.com/assets/818635/8301536/7526836e-1986-11e5-82fb-43c6377b6336.png)
![screen shot 2015-06-23 at 09 00 17](https://cloud.githubusercontent.com/assets/818635/8301537/752f850e-1986-11e5-99a1-a44456f31253.png)

Is there any way to bring back the old code highlighting from version 1?

**Comment by BenParizek** [comment]
Hi Katrin,

The syntax highlighting situation is a bit like whack-a-mole.  The changes that I made were an attempt to make syntax highlighting more standardize across several themes.  The challenge is that each person who makes a theme decides which scopes (like css classes for the text editor) they choose to support, and if you compare different themes, it's hard to find much consistency between what's supported.

I'm hoping to record a short screencast on the topic and share a bit more about how to update a theme to be more in line with what you want.  The best path right now may be to test a few other themes or try out the two themes included with the Craft-Twig package:
https://github.com/BarrelStrength/Craft-Twig.tmbundle/tree/master/Themes

There is also a fairly comprehensive test file to review how themes work with all the different Craft/Twig tags here:
https://github.com/BarrelStrength/Craft-Twig.tmbundle/blob/master/Extras/Craft-Twig%20Unit%20Test.twig

**Comment by katrinkerber** [comment]
Thanks Ben. I did try the themes included but they look the same in terms of differentiation between the words, only with different colours.

Is there any way that I could revert back to the old highlighting without affecting the newly added tab triggers?

**Comment by BenParizek** [comment]
You could potentially grab the old `.tmLanguage` file from 1.0 and drop it into the latest package:
https://github.com/BarrelStrength/Craft-Twig.tmbundle/tree/v1.0.0/Syntaxes

I have not tested that so results may vary and you may need to restart or clear cache and all that jazz.  I also expect upgrading will need to be done manually after that.

I know how important our preferred color themes are and, while I can't promise quick results, it's something I'd like to support better over time. Would you mind sharing the names of the themes your using and unhappy with?

**Comment by katrinkerber** [comment]
Thank you Ben, dropping in those older Syntax files worked a treat :)

I *think* any theme I would have tried with the latest settings would have looked the same in terms of lack of colour differentiation. I am using the Spacegray theme and did try both the Artisan themes and they looked the same (with different colours of course).

If you look at the screenshots I've sent the things that weren't ideal for me in version 2 was the same colour used for Twig’s `sets` and `ifs` etc and HTML elements. The Twig code inside meta and body tags also had almost no colour differentiation.

Having said all this, I can imagine setting these things up is a lot of work and I'm happy with keeping those old files and remembering to do manual upgrades :)
