### ISSUE TITLE
Little bug in includejs completion

### ISSUE THREAD

**Issue by bossanova808** [BarrelStrength/Craft-Twig.tmbundle#14]
includejs [tab] gives

```
{% set js %}
    // JS here
    
{% endset %} 

{% includeCss js %}
```

Which puts the script in the head as CSS :)  - notice that last line.

**Comment by BenParizek** [comment]
@bossanova808 

This bug has been addressed in the latest release, and the syntax has also changed to now support the new tag pairs for `includecss`, `includehirescss`, and `includejs`

https://github.com/BarrelStrength/Craft-Twig.tmbundle/releases/tag/v2.0.2
