### ISSUE TITLE
Sublime Text throws regex error

### ISSUE THREAD

**Issue by mattstein** [BarrelStrength/Craft-Twig.tmbundle#15]
With Sublime Text 3 (stable, build 3083) I'm suddenly getting a regex error when I first launch Sublime and load/activate a `.twig` file:

> Error loading syntax file "Packages/Craft-Twig/Craft-Twig.tmbundle-2.0.2/Syntaxes/Craft-Twig.tmLanguage": Error in regex: target of repeat operator is not specified in regex (?ix)   # Enable free spacing mode, case insensitive
>			         # Adding parentheses around this pattern breaks things
>			         ?<=\{\%\s\bincludecss\b|\bincludehirescss\b\s\%\}

I cleared the relevant Library caches [as suggested here](https://github.com/BarrelStrength/Craft-Twig.tmbundle/issues/10) and reinstalled several times, both HEAD and latest release, and I can't seem to find my way out of this error. I loaded up different templates, some complex and others very simple, and experience the same thing regardless of what I do.

I've also installed manually and via Package Control.

Anything else I can try?

**Comment by BenParizek** [comment]
Hey Matt,

Looks like that might relate to some syntax just pushed in the latest release.  I've updated things, but haven't cut another release yet, so would you mind grabbing the latest zip from master and seeing if that solves things: https://github.com/BarrelStrength/Craft-Twig.tmbundle/archive/master.zip

**Comment by mattstein** [comment]
Back to pure bliss, thanks for the alarmingly fast response+fix @BenParizek!

**Comment by BenParizek** [comment]
Excellent.  I wasn't able to sleep last night as I felt that regex was off, but just didn't prove it locally. Your ticket had the amazing affect of making me immediately realize a fix!

I've cut a new bugfix release with the fix:
https://github.com/BarrelStrength/Craft-Twig.tmbundle/releases/tag/v2.0.3

**Comment by mattstein** [comment]
Sleep well tonight, @BenParizek :)

**Comment by since1976** [comment]
I'm getting a similar error message using 2.0.3. Have cleared all caches etc too.
``Error loading syntax file "Packages/Craft-Twig/Syntaxes/Craft-Twig.tmLanguage": Error in regex: invalid pattern in look-behind in regex (?ix)   # Enable free spacing mode, case insensitive
			         (?<=(\{\%\s\bincludecss\b\s\%\}|(\{\%\s\bincludehirescss\b\s\%\})))
``

**Comment by BenParizek** [comment]
@since1976 I just released 2.0.4. Can you give that a shot?  I'm seeing different results in how these regexes are validating in different editors, but I think I've got it: https://github.com/BarrelStrength/Craft-Twig.tmbundle/releases/tag/v2.0.4

**Comment by mattstein** [comment]
@BenParizek @since1976 FWIW I can confirm that 2.0.4 and Sublime Text are happy over here.

**Comment by since1976** [comment]
Can confirm that this latest release fixed the issue I was having. Thanks Ben
