### ISSUE TITLE
snippets should have tabs instead of spaces

### ISSUE THREAD

**Issue by jordanlev** [barrelstrength/Craft-Twig.tmbundle#16]
As per the sublime text docs here: http://sublimetext.info/docs/en/extensibility/snippets.html#snippets-file-format
(see the **content** section):

> When writing a snippet that contains indentation, always use tabs. The tabs will be transformed into spaces when the snippet is inserted if the option translateTabsToSpaces is set to true.

The snippets in this package have spaces instead of tabs, which means they aren't honoring the tabs setting in Sublime.

**Comment by jordanlev** [comment]
(Just to be clear, I am *not* trying to get into an argument about whether tabs-vs-spaces is better... rather utilizing tabs in the snippet allows Sublime to make them work with whichever setting the user has, whereas using spaces in the snippet always forces spaces on the user)

**Comment by BenParizek** [comment]
@jordanlev This has been addressed in the latest release (v4.0.0) with Craft 3 support. All snippets should now be using tabs, as recommended by Sublime.

As this is a major release, see the upgrade notes if you run into any issues: 
https://github.com/barrelstrength/Craft-Twig.tmbundle#installation
