### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by dorothyDorothy** [barrelstrength/Craft-Twig.tmbundle#19]
Hi,
I've just installed Craft-Twig and it's a really handy syntax highlighter but I'm having some trouble keeping it working.

I have **Sublime Text 3** build **3126** installed on **Ubuntu 16.04**

When I restart Sublime text I get this message:

> Error loading syntax file "Packages/Craft-Twig/Craft-Twig.tmLanguage": Unable to open Packages/Craft-Twig/Craft-Twig.tmLanguage

Also the syntax Highlighting disappears when the file you are working on is saved.  You can get the syntax to work again if you re-select craft-twig as the syntax.

I have tried the following: 

1. Remove the package
2. Exit Sublime Text
3. Restart Sublime Text
4. install craft-twig

This does not work and I cannot find any reference to craft-twig outside of the Installed Packages folder.

How can I fix this?

**Comment by dorothyDorothy** [comment]
OK, so I have discovered that saving the template files as .twig works much better but I am still getting the 

> Error loading syntax file "Packages/Craft-Twig/Craft-Twig.tmLanguage": Unable to open Packages/Craft-Twig/Craft-Twig.tmLanguage

message.
At least the syntax highlighting is working but it would be good to get rid of the annoying message.  Where should this package be saved on Ubuntu?  Could it be a permissions error on the file system?
Thanks,
Dorothy

**Comment by BenParizek** [comment]
Hi Dorothy. I haven't tested the bundle on Ubuntu, but expect the error may be more specific to Sublime Text than the operating system.

It appears there are several threads with people having similar issues on other operating systems too: I searched "Error loading syntax file" and found this thread which has a few folks explaining what they did to fix the issue on OSX:
https://forum.sublimetext.com/t/error-loading-syntax-file-each-time-after-opening-st2/6474
