### ISSUE TITLE
Does not activate in PHPStorm version 2017.1.2

### ISSUE THREAD

**Issue by Anubarak** [barrelstrength/Craft-Twig.tmbundle#23]
Hello,

Maybe I did some mistakes but some other with more experience than me were also not able to activate your bundle.
We use PHPStorm and included your bundle 
![twig](https://user-images.githubusercontent.com/6122122/28156072-73f6d32e-67b1-11e7-9967-6a68fc596aa2.PNG)

Do we have to do something else or why doesn't it work at all?
When I type `asset` and press `TAB` then it is transformed to `<asset></asset>` 
When I unregister  the native file type from PHPstorm I receive plain text without any syntax highlighting in my twig files but they are activated in my File Types

![files](https://user-images.githubusercontent.com/6122122/28156529-72c6e96a-67b3-11e7-99eb-e108e1c9156b.PNG)

Could you help me please?
I appreciate your help

**Comment by BenParizek** [comment]
HI @Anubarak 

I never had any luck getting PhpStorm to recognize the Textmate Bundle either. I did create similar packages for PhpStorm and I would recommend using those instead:

https://github.com/barrelstrength/PhpStorm-Live-Templates-Craft-CMS
https://github.com/barrelstrength/PhpStorm-Live-Templates-Twig-Extended
