### ISSUE TITLE
Extra bracket in include - {% include 'template' }%}

### ISSUE THREAD

**Issue by stereomyth** [barrelstrength/Craft-Twig.tmbundle#24]
Despite both #18 and #17 being merged, I am still getting that damn extra bracket after pressing tab.

I am using Craft-Twig v3.0.0 on Sublime Text 3 (OSX) installed with Sublime Package Control.

**Comment by darylknight** [comment]
Yep, me too. I can see it's attempted to be fixed at some point, but after typing `include` and pressing tab, I'm still getting: 

`{% include 'template' }%}`

**Comment by BenParizek** [comment]
@stereomyth @darylknight Thanks for calling this out. I think the main problem is me not understanding how to get a release updated on Package Control. I've cut a new release and tested. I still don't see the updates on Package Control, so if you'd like the fix you may want to download and install manually.

Latest release v3.0.3
https://github.com/barrelstrength/Craft-Twig.tmbundle/releases/tag/v3.0.3

Steps to install manually in Sublime:
https://github.com/barrelstrength/Craft-Twig.tmbundle/tree/v3.0.3#sublime-text
