### ISSUE TITLE
syntax highlighting in js and css tags

### ISSUE THREAD

**Issue by michel-o** [barrelstrength/Craft-Twig.tmbundle#25]
Can you please add syntax highlighting for css and js code inside `{% css %}` and `{% js %} `tags?

**Comment by BenParizek** [comment]
@michel-o We'll add this to our list and address it when we have a chance. Feel free to submit a pull request in the meantime.

**Comment by BenParizek** [comment]
@michel-o This has been added in v4.0.0 which has just been released and also adds Craft 3 support. `{% css %}` and `{% js %}` tags now have syntax highlighting support.

As this is a major release, please see the upgrade notes if you run into any issues:
https://github.com/barrelstrength/Craft-Twig.tmbundle#installation
