### ISSUE TITLE
Add Craft 3 support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/Craft-Twig.tmbundle#26]

**Comment by bgarrant** [comment]
Do you have plans to add Craft 2 support Ben?

**Comment by BenParizek** [comment]
@bgarrant Craft 3 support has just been released. You may need to uninstall the current package, restart Sublime Text, and install the new package fresh. See the upgrade notes here:
https://github.com/barrelstrength/Craft-Twig.tmbundle#installation
