### ISSUE TITLE
bundle lacks mandatory keys

### ISSUE THREAD

**Issue by heidmous** [BarrelStrength/Craft-Twig.tmbundle#8]
Hey, thanks for all the great tools from BarrelStrength.  I've cloned over the Craft-Twig.tmbundle every which way I know how and can't avoid getting this message when i try to pull it into TextMate. 

**The bundle " Craft-Twig " could not be installed because it is malformed** - *the bundle lacks mandatory keys in its property list.*

Is this something you can help me with on your end?  Thanks!

**Comment by BenParizek** [comment]
@heidmous Thanks for the feedback.  I've marked this as an enhancement.

While this bundle was branched from a Textmate bundle, all updates made to it were done only with Sublime Text in mind, so Textmate compatibility is not supported at the moment.

If you'd like to help make those updates, I could use a hand, and would happily review the pull request.  I'm personally not familiar with writing Textmate bundles so there is some learning curve preventing me from just updating things without finding the time to learn about that first.  I would like to update things to be Textmate compatible – to make the bundle compatible with Textmate and potentially other editors too, like PHPStorm.

**Comment by heidmous** [comment]
Hey Ben,

I am fairly new to programming and am teaching myself - which is fun and
challenging.  Thus far, all the hang-up's I seem to have are minutia not
big picture ( like one week delay troubleshooting missing colon !!!
aaahhh)  haha.

That being said, I see projects like this one as being a great an
opportunity to gain some insight into how more of these layered programs
work.  I could embark on this learning experience with you.  If you don't
really have time for it I may just seek other options due to the fact that
in triage I have some more important things to learn first.

Thanks for the explanation about the adaptation of the .tmbundle with
sublime text in mind.  That makes sense.  I thought tmbundle was a Text
Mate specific extension so I was assuming it was a missing folder or
version issue.

Let me know if you want to tackle this project together, I could put some
time into it.

On Tue, May 12, 2015 at 9:49 PM, Ben Parizek <notifications@github.com>
wrote:

> @heidmous <https://github.com/heidmous> Thanks for the feedback. I've
> marked this as an enhancement.
>
> While this bundle was branched from a Textmate bundle, all updates made to
> it were done only with Sublime Text in mind, so Textmate compatibility is
> not supported at the moment.
>
> If you'd like to help make those updates, I could use a hand, and would
> happily review the pull request. I'm personally not familiar with writing
> Textmate bundles so there is some learning curve preventing me from just
> updating things without finding the time to learn about that first. I would
> like to update things to be Textmate compatible – to make the bundle
> compatible with Textmate and potentially other editors too, like PHPStorm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BarrelStrength/Craft-Twig.tmbundle/issues/8#issuecomment-101504694>
> .
>



-- 
Bryan N. Heidmous
bryan.heidmous@gmail.com
719 331 2611

**Comment by BenParizek** [comment]
Good to know @heidmous.  

Right now, I don't have enough free time to dive into this, but when that changes, I'll reach out and see if you're still interested.  First step will just be trying to find a good spec on how to create a TextMate plugin!

**Comment by heidmous** [comment]
Hey Ben,

Textmate 2.0 comes with the bundle built in... I just had to upgrade my
install and boom, there goes the dynamite.

Thanks again for the things you share with other developers.

bryan

On Fri, May 15, 2015 at 1:20 AM, Ben Parizek <notifications@github.com>
wrote:

> Good to know @heidmous <https://github.com/heidmous>.
>
> Right now, I don't have enough free time to dive into this, but when that
> changes, I'll reach out and see if you're still interested. First step will
> just be trying to find a good spec on how to create a TextMate plugin!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BarrelStrength/Craft-Twig.tmbundle/issues/8#issuecomment-102297909>
> .
>



-- 
Bryan N. Heidmous
bryan.heidmous@gmail.com
719 331 2611

**Comment by BenParizek** [comment]
@heidmous This conversation struck up my interest in Language Grammars again.  I've migrated the Craft-Twig bundle back to being a native Textmate bundle, with some additions for Sublime Text, so the bundle should be good to go in both editors now.  I rewrote almost the entire Language Grammar, and tried to add a ton more comments to make future updates and collaboration a bit easier.  I've got a post half-pulled-together as well documenting the process a bit more that I'll link in the README whenever I complete it.

You can grab the latest on the releases tab:
https://github.com/BarrelStrength/Craft-Twig.tmbundle/releases
